[package]
name = "max30009"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Embedded Rust driver for MAX30009 impedance measurement IC"
repository = "https://github.com/louisreg/max30009-rs"

[dependencies]
embedded-hal = "1.0.0"
bitflags = "2"
thiserror = { version = "2.0.18", default-features = false }

[dev-dependencies]
embedded-hal-mock = "0.11.1"

[features]
default = []
